version: '3'
services:
  jenkins:
    build:
        context: ./docker/jenkins
        dockerfile: Dockerfile
    container_name: jenkins
    ports:
      - '8080:8080'
      - '8443:8443'
      - '50000:50000'
    volumes:
      - './docker/volumes/jenkins/data:/bitnami'
        # hook the daemon's unix socket to the host machine's docker unix socket
      - '/var/run/docker.sock:/var/run/docker.sock'
